export type Locale = 'en' | 'nl'

type CopyTree = Record<string, string>

const en: CopyTree = {
  'tabs.home': 'Home',
  'tabs.messages': 'Messages',
  'tabs.assistant': 'Assistant',
  'tabs.decisions': 'Decisions',
  'inbox.visitor': 'Website visitor',
  'tabs.settings': 'Settings',

  'login.brand': 'Bokito',
  'login.tagline': 'Inbox, assistants and approvals — in one place.',
  'login.subtitle': 'Sign in to your workspace',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.invalid': 'Email or password is not correct.',
  'login.offline': 'Could not reach Bokito. Check your connection and try again.',
  'login.twoFactorTitle': 'Confirm it is you',
  'login.twoFactorBody': 'Enter the 6-digit code from your authenticator app.',
  'login.twoFactorCode': 'Verification code',
  'login.twoFactorSubmit': 'Continue',
  'login.twoFactorInvalid': 'That code is not valid. Try again.',
  'login.back': 'Back to sign in',
  'login.forgot': 'Forgot password?',
  'login.forgotSent': 'If that email exists, we sent a reset link.',
  'login.forgotNeedEmail': 'Enter your email first.',
  'login.devFill': 'Use local test account',

  'home.loopTitle': 'How Bokito fits together',
  'home.loopHint': 'Messages, assistants and approvals are one loop.',
  'home.loopMessages': 'Messages',
  'home.loopMessagesHint': 'Customer and team conversations land here.',
  'home.loopAgents': 'Assistant',
  'home.loopAgentsHint': 'Ask your agent, or let it draft replies.',
  'home.loopGovern': 'Decisions',
  'home.loopGovernHint': 'Approve what may run without you.',
  'home.loopDismiss': 'Hide',
  'home.attention': 'Needs you',
  'home.recent': 'Recent messages',
  'home.openMessages': 'Customer messages',
  'home.waitingDecisions': 'Waiting on you',
  'home.askAssistant': 'Ask your assistant',
  'home.askAssistantHint': 'Questions about this workspace, drafts, or next steps.',
  'home.emptyAttention': 'Nothing waiting. Assistants are working within policy.',
  'home.loadError': 'Could not load this overview.',
  'home.seeAll': 'See all',
  'home.workspace': 'Workspace',
  'home.connected': 'Connected',
  'home.connecting': 'Connecting',
  'home.offline': 'Offline',
  'home.autonomy': '{pct}% handled automatically',
  'home.notifications': 'Notifications',
  'home.unreadCount': '{count} unread',

  'inbox.search': 'Search this folder',
  'inbox.filters': 'Filters',
  'inbox.open': 'Open',
  'inbox.mine': 'Mine',
  'inbox.unassigned': 'Unassigned',
  'inbox.decisions': 'Decisions',
  'inbox.allChannels': 'All channels',
  'inbox.allFolders': 'All',
  'inbox.external': 'Customers',
  'inbox.internal': 'Team',
  'inbox.empty': 'No conversations in this view.',
  'inbox.emptyHint': 'New customer and team messages appear here.',
  'inbox.emptyCustomers': 'No customer conversations yet.',
  'inbox.emptyCustomersHint': 'Customer email and website chat land here. Connect a channel in the workspace.',
  'inbox.emptyTeam': 'No team conversations yet.',
  'inbox.emptyTeamHint': 'Internal agent runs and team chats appear here.',
  'inbox.emptyDecisions': 'No decisions in the inbox right now.',
  'inbox.emptyDecisionsHint': 'Customer and team decisions both appear here.',
  'inbox.openChannels': 'Open channels in the workspace',
  'inbox.newChat': 'New assistant chat',
  'inbox.openAssistant': 'Ask the assistant',
  'inbox.noSubject': 'No subject',
  'inbox.unknownSender': 'Unknown sender',
  'inbox.closed': 'Closed',
  'inbox.pending': 'Pending',
  'inbox.error': 'Could not load conversations.',
  'inbox.compose': 'New conversation',
  'inbox.composeHint': 'Start a customer conversation in the workspace, or a new assistant chat here.',
  'inbox.newCustomer': 'New customer conversation',
  'inbox.refreshFailed': 'Could not refresh this list.',
  'inbox.updates': 'Updates',
  'inbox.results': 'Results',
  'inbox.snoozed': 'Snoozed',
  'inbox.spam': 'Spam',
  'inbox.emptySnoozed': 'Nothing snoozed.',
  'inbox.emptySnoozedHint': 'Snoozed customer conversations wait here until they come back.',
  'inbox.emptySpam': 'No spam in this folder.',
  'inbox.emptyUpdates': 'No agent updates yet.',
  'inbox.emptyUpdatesHint': 'Status updates from agent runs land here.',
  'inbox.emptyResults': 'No agent results yet.',
  'inbox.emptyResultsHint': 'Completed agent work shows up here.',
  'inbox.pinned': 'Pinned',
  'inbox.emptyPinned': 'No pinned conversations.',
  'inbox.urgent': 'Urgent',
  'inbox.high': 'High',

  'live.paused': 'Live updates are paused. New messages may be late.',
  'live.connecting': 'Reconnecting to live updates.',
  'live.retry': 'Retry',

  'thread.title': 'Conversation',
  'thread.screenTitle': 'Conversation',
  'thread.empty': 'No messages yet.',
  'thread.pin': 'Pin',
  'thread.unpin': 'Unpin',
  'thread.close': 'Close',
  'thread.reopen': 'Reopen',
  'thread.markUnread': 'Mark unread',
  'thread.takeover': 'Take over',
  'thread.release': 'Release to AI',
  'thread.delete': 'Delete',
  'thread.deleteTitle': 'Delete conversation',
  'thread.deleteBody': 'This conversation will be permanently deleted.',
  'thread.cancel': 'Cancel',
  'thread.aiPaused': 'You are handling this conversation. AI will not reply until you release it.',
  'thread.contactTitle': 'Contact',
  'thread.contactThreads': 'conversations',
  'thread.reply': 'Reply',
  'thread.note': 'Note',
  'thread.replyPlaceholder': 'Write a reply',
  'thread.replyPlaceholderEmail': 'Reply to {name}',
  'thread.replyPlaceholderChat': 'Reply in chat to {name}',
  'thread.replyPlaceholderSlack': 'Write a Slack message',
  'thread.replyPlaceholderWhatsapp': 'Reply on WhatsApp to {name}',
  'thread.replyPlaceholderAgent': 'Message {name}',
  'thread.replyEmail': 'Email',
  'thread.replyChat': 'Chat',
  'thread.replySlack': 'Slack',
  'thread.replyWhatsapp': 'WhatsApp',
  'thread.recipientTo': 'To',
  'thread.recipientWith': 'With',
  'thread.recipientChannel': 'Channel',
  'thread.recipientAgent': 'Agent',
  'thread.loadError': 'Could not open this conversation.',
  'thread.notFound': 'This conversation is no longer available.',
  'thread.sendFailed': 'Could not send',
  'thread.sendFailedBody': 'Check your connection and try again.',
  'thread.notePlaceholder': 'Internal note',
  'thread.openContactWeb': 'Open contact in workspace',
  'thread.sendPending': 'Send and pending',
  'thread.sendClose': 'Send and close',
  'thread.clearAttachments': 'Clear attachments',
  'thread.today': 'Today',
  'thread.yesterday': 'Yesterday',
  'thread.internalNote': 'Internal note',
  'thread.decisionRequested': 'Decision requested',
  'thread.resolved': 'Resolved',
  'thread.defer': 'Later',
  'thread.uploadFailed': 'Upload failed',
  'thread.uploadFailedBody': 'Could not upload the selected file.',
  'thread.assignMe': 'Assign to me',
  'thread.unassign': 'Unassign',
  'thread.askAssistant': 'Ask assistant about this',
  'thread.actionFailed': 'Could not update this conversation',
  'thread.actionFailedBody': 'Check your connection and try again.',
  'thread.spam': 'Mark as spam',
  'thread.snooze': 'Snooze until tomorrow',
  'thread.unsnooze': 'Unsnooze',
  'thread.draftReply': 'Draft a reply',
  'thread.draftFailed': 'Could not draft a reply.',
  'thread.invokeAgent': 'Run agent on this thread',
  'thread.invokeFailed': 'The agent could not run on this thread.',
  'thread.invokeOk': 'The agent is working on this thread.',
  'thread.savedReplies': 'Saved replies',
  'thread.noSavedReplies': 'No saved replies yet. Add them in the workspace.',
  'thread.contactNotes': 'Notes',
  'thread.contactOther': 'Other conversations',
  'thread.contactSave': 'Save notes',
  'thread.contactSaved': 'Notes saved.',
  'thread.assignTo': 'Assign',
  'thread.assignFailed': 'Could not find you in this workspace.',
  'thread.sendAsYou': 'Send as you',
  'thread.sendAsAgent': 'Send as agent',
  'thread.sendAsTitle': 'Who should send this reply?',
  'thread.sendStatusFailed': 'This message was not delivered.',
  'thread.sendStatusScheduled': 'Scheduled. Not sent yet.',
  'thread.cancelSend': 'Cancel send',
  'thread.feedbackUp': 'Helpful',
  'thread.feedbackDown': 'Not helpful',
  'thread.editNote': 'Edit note',
  'thread.deleteNote': 'Delete note',
  'thread.deleteNoteTitle': 'Delete this note?',
  'thread.you': 'You',
  'thread.ai': 'AI',
  'thread.team': 'Team',

  'decisions.empty': 'No decisions waiting on you. Agents are running within policy.',
  'decisions.emptyHint': 'When an agent needs a human, it shows up here and in the conversation.',
  'decisions.openThread': 'Open conversation',
  'decisions.approve': 'Approve',
  'decisions.reject': 'Reject',
  'decisions.error': 'Could not save that decision. Try again.',
  'decisions.loadError': 'Could not load decisions.',
  'decisions.openMessages': 'Open messages',

  'assistant.empty': 'Ask anything about this workspace — drafts, customers, or what to do next.',
  'assistant.emptyHint': 'This is the same assistant as in the workspace.',
  'agent.working': 'Looking something up',
  'agent.done': 'Finished looking up',
  'agent.thinking': 'Thinking',
  'agent.thinkingActive': 'Thinking...',
  'agent.using': 'Running {name}',
  'agent.finished': 'Finished {name}',
  'agent.whatDid': 'What the agent did',
  'agent.knowledge': 'Knowledge',
  'agent.knowledgeDone': 'Knowledge',
  'agent.consultingKnowledge': 'Consulting knowledge',
  'agent.consultedKnowledge': 'Consulted knowledge',
  'agent.updatingKnowledge': 'Updating knowledge',
  'agent.updatedKnowledge': 'Updated knowledge',
  'assistant.sendFailed': 'Could not send that message. Try again.',
  'assistant.placeholder': 'Message your assistant',
  'assistant.new': 'New',
  'assistant.conversations': 'Conversations',
  'assistant.agent': 'Agent',
  'assistant.history': 'History',
  'assistant.untitled': 'Untitled',
  'assistant.noConversations': 'No conversations yet.',
  'assistant.defaultTitle': 'Assistant',
  'assistant.newTitle': 'New conversation',
  'assistant.loadError': 'Could not load assistant chats.',
  'assistant.deleteTitle': 'Delete this chat?',
  'assistant.deleteBody': 'This assistant conversation will be permanently deleted.',
  'assistant.actionFailed': 'Could not update that chat.',

  'settings.signedIn': 'Signed in as',
  'settings.workspace': 'Workspace',
  'settings.role': 'Role',
  'settings.connection': 'Live connection',
  'settings.appearance': 'Appearance',
  'settings.appearanceHint': 'Matches the workspace Light and Dark themes.',
  'settings.appearanceLight': 'Light',
  'settings.appearanceDark': 'Dark',
  'settings.appearanceSystem': 'System',
  'settings.language': 'Language',
  'settings.languageEn': 'English',
  'settings.languageNl': 'Nederlands',
  'settings.notifications': 'Notifications on this device',
  'settings.notificationsHint': 'Same categories as the web app. Desktop alerts also drive mobile push.',
  'settings.pushOn': 'Push is registered on this device.',
  'settings.pushOff': 'Push is not available here (simulator or permission denied).',
  'settings.pushRetry': 'Enable notifications',
  'settings.openWeb': 'Open workspace in browser',
  'settings.openWebHint': 'Agents, contacts, agenda and settings live on the full workspace.',
  'settings.advanced': 'Advanced',
  'settings.endpoint': 'Connected to',
  'settings.signOut': 'Sign out',
  'settings.pref.assigned-to-me': 'When a conversation is assigned to you',
  'settings.pref.mentions': 'When you are mentioned',
  'settings.pref.decisions': 'When an agent needs your decision',
  'settings.pref.handoff': 'When someone asks for a human',
  'settings.saved': 'Saved',
  'settings.saveFailed': 'Could not save preferences.',
  'settings.switchWorkspace': 'Switch workspace',
  'settings.notificationsInbox': 'Notification inbox',
  'settings.notificationsInboxHint': 'Mentions, assignments and decisions.',
  'settings.emptyPrefs': 'Using default alerts until preferences load.',

  'notifications.title': 'Notifications',
  'notifications.empty': 'No notifications yet.',
  'notifications.emptyHint': 'Bokito notifies you when a customer writes or an agent needs a decision.',
  'notifications.markAll': 'Mark all read',
  'notifications.error': 'Could not load notifications.',
  'notifications.markAllFailed': 'Could not mark notifications as read.',
  'home.summaryFailed': 'Could not load autonomy stats.',

  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.retry': 'Try again',
  'common.now': 'now',
}

const nl: CopyTree = {
  'tabs.home': 'Home',
  'tabs.messages': 'Berichten',
  'tabs.assistant': 'Assistent',
  'tabs.decisions': 'Beslissingen',
  'tabs.settings': 'Instellingen',

  'login.brand': 'Bokito',
  'login.tagline': 'Inbox, assistenten en goedkeuringen — op één plek.',
  'login.subtitle': 'Log in op je workspace',
  'login.email': 'E-mail',
  'login.password': 'Wachtwoord',
  'login.submit': 'Inloggen',
  'login.invalid': 'E-mail of wachtwoord klopt niet.',
  'login.offline': 'Bokito is niet bereikbaar. Controleer je verbinding.',
  'login.twoFactorTitle': 'Bevestig dat jij het bent',
  'login.twoFactorBody': 'Vul de 6-cijferige code uit je authenticator-app in.',
  'login.twoFactorCode': 'Verificatiecode',
  'login.twoFactorSubmit': 'Doorgaan',
  'login.twoFactorInvalid': 'Die code is niet geldig. Probeer opnieuw.',
  'login.back': 'Terug naar inloggen',
  'login.forgot': 'Wachtwoord vergeten?',
  'login.forgotSent': 'Als dat e-mailadres bestaat, hebben we een resetlink gestuurd.',
  'login.forgotNeedEmail': 'Vul eerst je e-mailadres in.',
  'login.devFill': 'Gebruik lokaal testaccount',

  'home.loopTitle': 'Hoe Bokito samenhangt',
  'home.loopHint': 'Berichten, assistenten en goedkeuringen zijn één loop.',
  'home.loopMessages': 'Berichten',
  'home.loopMessagesHint': 'Klant- en teamgesprekken komen hier binnen.',
  'home.loopAgents': 'Assistent',
  'home.loopAgentsHint': 'Stel een vraag, of laat de agent antwoorden opstellen.',
  'home.loopGovern': 'Beslissingen',
  'home.loopGovernHint': 'Jij bepaalt wat zonder jou mag lopen.',
  'home.loopDismiss': 'Verbergen',
  'home.attention': 'Vraagt om jou',
  'home.recent': 'Recente berichten',
  'home.openMessages': 'Klantberichten',
  'home.waitingDecisions': 'Wacht op jou',
  'home.askAssistant': 'Vraag je assistent',
  'home.askAssistantHint': 'Vragen over deze workspace, concepten of volgende stappen.',
  'home.emptyAttention': 'Niets in de wacht. Assistenten werken binnen het beleid.',
  'home.loadError': 'Dit overzicht kon niet worden geladen.',
  'home.seeAll': 'Alles',
  'home.workspace': 'Workspace',
  'home.connected': 'Verbonden',
  'home.connecting': 'Verbinden',
  'home.offline': 'Offline',
  'home.autonomy': '{pct}% automatisch afgehandeld',
  'home.notifications': 'Meldingen',
  'home.unreadCount': '{count} ongelezen',

  'inbox.search': 'Zoek in deze map',
  'inbox.filters': 'Filters',
  'inbox.open': 'Open',
  'inbox.mine': 'Van mij',
  'inbox.unassigned': 'Niet toegewezen',
  'inbox.decisions': 'Beslissingen',
  'inbox.allChannels': 'Alle kanalen',
  'inbox.allFolders': 'Alles',
  'inbox.external': 'Klanten',
  'inbox.internal': 'Team',
  'inbox.empty': 'Geen gesprekken in dit overzicht.',
  'inbox.emptyHint': 'Nieuwe klant- en teamberichten verschijnen hier.',
  'inbox.emptyCustomers': 'Nog geen klantgesprekken.',
  'inbox.emptyCustomersHint': 'Klantmail en websitechat landen hier. Koppel een kanaal in de workspace.',
  'inbox.emptyTeam': 'Nog geen teamgesprekken.',
  'inbox.emptyTeamHint': 'Interne agent-runs en teamchats verschijnen hier.',
  'inbox.emptyDecisions': 'Geen beslissingen in de inbox.',
  'inbox.emptyDecisionsHint': 'Klant- en teambeslissingen verschijnen hier allebei.',
  'inbox.openChannels': 'Kanalen openen in de workspace',
  'inbox.newChat': 'Nieuw assistentgesprek',
  'inbox.visitor': 'Websitebezoeker',
  'inbox.openAssistant': 'Vraag de assistent',
  'inbox.noSubject': 'Geen onderwerp',
  'inbox.unknownSender': 'Onbekende afzender',
  'inbox.closed': 'Gesloten',
  'inbox.pending': 'In afwachting',
  'inbox.error': 'Gesprekken konden niet worden geladen.',
  'inbox.compose': 'Nieuw gesprek',
  'inbox.composeHint': 'Start een klantgesprek in de workspace, of een nieuw assistentgesprek hier.',
  'inbox.newCustomer': 'Nieuw klantgesprek',
  'inbox.refreshFailed': 'Deze lijst kon niet worden vernieuwd.',
  'inbox.updates': 'Updates',
  'inbox.results': 'Resultaten',
  'inbox.snoozed': 'Uitgesteld',
  'inbox.spam': 'Spam',
  'inbox.emptySnoozed': 'Niets uitgesteld.',
  'inbox.emptySnoozedHint': 'Uitgestelde klantgesprekken komen hier terug.',
  'inbox.emptySpam': 'Geen spam in deze map.',
  'inbox.emptyUpdates': 'Nog geen agent-updates.',
  'inbox.emptyUpdatesHint': 'Statusupdates van agent-runs landen hier.',
  'inbox.emptyResults': 'Nog geen agentresultaten.',
  'inbox.emptyResultsHint': 'Afgerond agentwerk verschijnt hier.',
  'inbox.pinned': 'Vastgezet',
  'inbox.emptyPinned': 'Geen vastgezette gesprekken.',
  'inbox.urgent': 'Urgent',
  'inbox.high': 'Hoog',

  'live.paused': 'Live updates staan stil. Nieuwe berichten kunnen later binnenkomen.',
  'live.connecting': 'Opnieuw verbinden met live updates.',
  'live.retry': 'Opnieuw',

  'thread.title': 'Gesprek',
  'thread.screenTitle': 'Gesprek',
  'thread.empty': 'Nog geen berichten.',
  'thread.pin': 'Vastzetten',
  'thread.unpin': 'Losmaken',
  'thread.close': 'Sluiten',
  'thread.reopen': 'Heropenen',
  'thread.markUnread': 'Markeer ongelezen',
  'thread.takeover': 'Overnemen',
  'thread.release': 'Teruggeven aan AI',
  'thread.delete': 'Verwijderen',
  'thread.deleteTitle': 'Gesprek verwijderen',
  'thread.deleteBody': 'Dit gesprek wordt definitief verwijderd.',
  'thread.cancel': 'Annuleren',
  'thread.aiPaused': 'Jij handelt dit gesprek af. AI antwoordt niet tot je het vrijgeeft.',
  'thread.contactTitle': 'Contact',
  'thread.contactThreads': 'gesprekken',
  'thread.reply': 'Antwoorden',
  'thread.note': 'Notitie',
  'thread.replyPlaceholder': 'Schrijf een antwoord',
  'thread.replyPlaceholderEmail': 'Antwoord aan {name}',
  'thread.replyPlaceholderChat': 'Antwoord in chat aan {name}',
  'thread.replyPlaceholderSlack': 'Schrijf een Slack-bericht',
  'thread.replyPlaceholderWhatsapp': 'Antwoord op WhatsApp aan {name}',
  'thread.replyPlaceholderAgent': 'Bericht aan {name}',
  'thread.replyEmail': 'E-mail',
  'thread.replyChat': 'Chat',
  'thread.replySlack': 'Slack',
  'thread.replyWhatsapp': 'WhatsApp',
  'thread.recipientTo': 'Aan',
  'thread.recipientWith': 'Met',
  'thread.recipientChannel': 'Kanaal',
  'thread.recipientAgent': 'Agent',
  'thread.loadError': 'Dit gesprek kon niet worden geopend.',
  'thread.notFound': 'Dit gesprek is niet meer beschikbaar.',
  'thread.sendFailed': 'Versturen mislukt',
  'thread.sendFailedBody': 'Controleer je verbinding en probeer opnieuw.',
  'thread.notePlaceholder': 'Interne notitie',
  'thread.openContactWeb': 'Contact openen in de workspace',
  'thread.sendPending': 'Verstuur en wacht',
  'thread.sendClose': 'Verstuur en sluit',
  'thread.clearAttachments': 'Bijlagen wissen',
  'thread.today': 'Vandaag',
  'thread.yesterday': 'Gisteren',
  'thread.internalNote': 'Interne notitie',
  'thread.decisionRequested': 'Besluit gevraagd',
  'thread.resolved': 'Afgehandeld',
  'thread.defer': 'Later',
  'thread.uploadFailed': 'Upload mislukt',
  'thread.uploadFailedBody': 'Het bestand kon niet worden geüpload.',
  'thread.assignMe': 'Wijs aan mij toe',
  'thread.unassign': 'Toewijzing verwijderen',
  'thread.askAssistant': 'Vraag de assistent hierover',
  'thread.actionFailed': 'Dit gesprek kon niet worden bijgewerkt',
  'thread.actionFailedBody': 'Controleer je verbinding en probeer opnieuw.',
  'thread.spam': 'Markeer als spam',
  'thread.snooze': 'Uitstellen tot morgen',
  'thread.unsnooze': 'Hervatten',
  'thread.draftReply': 'Conceptantwoord',
  'thread.draftFailed': 'Er kon geen concept worden gemaakt.',
  'thread.invokeAgent': 'Agent op dit gesprek zetten',
  'thread.invokeFailed': 'De agent kon dit gesprek niet oppakken.',
  'thread.invokeOk': 'De agent werkt aan dit gesprek.',
  'thread.savedReplies': 'Opgeslagen antwoorden',
  'thread.noSavedReplies': 'Nog geen opgeslagen antwoorden. Voeg ze toe in de workspace.',
  'thread.contactNotes': 'Notities',
  'thread.contactOther': 'Andere gesprekken',
  'thread.contactSave': 'Notities opslaan',
  'thread.contactSaved': 'Notities opgeslagen.',
  'thread.assignTo': 'Toewijzen',
  'thread.assignFailed': 'Jij staat niet in deze workspace.',
  'thread.sendAsYou': 'Verstuur als jij',
  'thread.sendAsAgent': 'Verstuur als agent',
  'thread.sendAsTitle': 'Wie verstuurt dit antwoord?',
  'thread.sendStatusFailed': 'Dit bericht is niet bezorgd.',
  'thread.sendStatusScheduled': 'Gepland. Nog niet verstuurd.',
  'thread.cancelSend': 'Versturen annuleren',
  'thread.feedbackUp': 'Nuttig',
  'thread.feedbackDown': 'Niet nuttig',
  'thread.editNote': 'Notitie bewerken',
  'thread.deleteNote': 'Notitie verwijderen',
  'thread.deleteNoteTitle': 'Deze notitie verwijderen?',
  'thread.you': 'Jij',
  'thread.ai': 'AI',
  'thread.team': 'Team',

  'decisions.empty': 'Geen beslissingen die op jou wachten. Assistenten lopen binnen het beleid.',
  'decisions.emptyHint': 'Als een assistent een mens nodig heeft, verschijnt dat hier en in het gesprek.',
  'decisions.openThread': 'Open gesprek',
  'decisions.approve': 'Goedkeuren',
  'decisions.reject': 'Afwijzen',
  'decisions.error': 'Beslissing kon niet worden opgeslagen. Probeer opnieuw.',
  'decisions.loadError': 'Beslissingen konden niet worden geladen.',
  'decisions.openMessages': 'Open berichten',

  'assistant.empty': 'Vraag wat je wilt over deze workspace — concepten, klanten of volgende stappen.',
  'assistant.emptyHint': 'Dit is dezelfde assistent als in de workspace.',
  'agent.working': 'Aan het opzoeken',
  'agent.done': 'Opzoeken klaar',
  'agent.thinking': 'Nadenken',
  'agent.thinkingActive': 'Aan het nadenken...',
  'agent.using': '{name} uitvoeren',
  'agent.finished': '{name} afgerond',
  'agent.whatDid': 'Wat de agent deed',
  'agent.knowledge': 'Kennis',
  'agent.knowledgeDone': 'Kennis',
  'agent.consultingKnowledge': 'Kennis raadplegen',
  'agent.consultedKnowledge': 'Kennis geraadpleegd',
  'agent.updatingKnowledge': 'Kennis bijwerken',
  'agent.updatedKnowledge': 'Kennis bijgewerkt',
  'assistant.sendFailed': 'Bericht kon niet worden verstuurd. Probeer opnieuw.',
  'assistant.placeholder': 'Bericht aan je assistent',
  'assistant.new': 'Nieuw',
  'assistant.conversations': 'Gesprekken',
  'assistant.agent': 'Agent',
  'assistant.history': 'Geschiedenis',
  'assistant.untitled': 'Naamloos',
  'assistant.noConversations': 'Nog geen gesprekken.',
  'assistant.defaultTitle': 'Assistent',
  'assistant.newTitle': 'Nieuw gesprek',
  'assistant.loadError': 'Assistentgesprekken konden niet worden geladen.',
  'assistant.deleteTitle': 'Dit gesprek verwijderen?',
  'assistant.deleteBody': 'Dit assistentgesprek wordt definitief verwijderd.',
  'assistant.actionFailed': 'Dat gesprek kon niet worden bijgewerkt.',

  'settings.signedIn': 'Ingelogd als',
  'settings.workspace': 'Workspace',
  'settings.role': 'Rol',
  'settings.connection': 'Live verbinding',
  'settings.appearance': 'Weergave',
  'settings.appearanceHint': 'Zelfde Licht- en Donkerthema als de workspace.',
  'settings.appearanceLight': 'Licht',
  'settings.appearanceDark': 'Donker',
  'settings.appearanceSystem': 'Systeem',
  'settings.language': 'Taal',
  'settings.languageEn': 'English',
  'settings.languageNl': 'Nederlands',
  'settings.notifications': 'Meldingen op dit apparaat',
  'settings.notificationsHint': 'Zelfde categorieën als in de webapp. Desktop-alerts sturen ook mobiele push.',
  'settings.pushOn': 'Push is geregistreerd op dit apparaat.',
  'settings.pushOff': 'Push is hier niet beschikbaar (simulator of geen toestemming).',
  'settings.pushRetry': 'Meldingen inschakelen',
  'settings.openWeb': 'Open workspace in de browser',
  'settings.openWebHint': 'Agents, contacten, agenda en instellingen staan in de volledige workspace.',
  'settings.advanced': 'Geavanceerd',
  'settings.endpoint': 'Verbonden met',
  'settings.signOut': 'Uitloggen',
  'settings.pref.assigned-to-me': 'Als een gesprek aan jou is toegewezen',
  'settings.pref.mentions': 'Als je wordt genoemd',
  'settings.pref.decisions': 'Als een agent jouw besluit nodig heeft',
  'settings.pref.handoff': 'Als iemand om een mens vraagt',
  'settings.saved': 'Opgeslagen',
  'settings.saveFailed': 'Voorkeuren konden niet worden opgeslagen.',
  'settings.switchWorkspace': 'Wissel van workspace',
  'settings.notificationsInbox': 'Meldingeninbox',
  'settings.notificationsInboxHint': 'Vermeldingen, toewijzingen en besluiten.',
  'settings.emptyPrefs': 'Standaardmeldingen tot voorkeuren laden.',

  'notifications.title': 'Meldingen',
  'notifications.empty': 'Nog geen meldingen.',
  'notifications.emptyHint': 'Bokito laat je weten wanneer een klant schrijft of een agent een beslissing nodig heeft.',
  'notifications.markAll': 'Alles gelezen',
  'notifications.error': 'Meldingen konden niet worden geladen.',
  'notifications.markAllFailed': 'Meldingen konden niet als gelezen worden gemarkeerd.',
  'home.summaryFailed': 'Autonomiecijfers konden niet worden geladen.',

  'common.cancel': 'Annuleren',
  'common.delete': 'Verwijderen',
  'common.retry': 'Opnieuw',
  'common.now': 'nu',
}

const tables: Record<Locale, CopyTree> = { en, nl }

export function copyKeys(locale: Locale): string[] {
  return Object.keys(tables[locale])
}

export function detectLocale(): Locale {
  try {
    const locale = Intl.DateTimeFormat().resolvedOptions().locale || ''
    return locale.toLowerCase().startsWith('nl') ? 'nl' : 'en'
  } catch {
    return 'en'
  }
}

export function translate(
  locale: Locale,
  key: string,
  vars?: Record<string, string | number>,
): string {
  let text = tables[locale][key] ?? tables.en[key] ?? key
  if (vars) {
    for (const [name, value] of Object.entries(vars)) {
      text = text.replaceAll(`{${name}}`, String(value))
    }
  }
  return text
}
